#修改TNAME:n56ub1_base 中的n56ub1_base为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同？
name: Build Padavan-new1

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
    branches: a
      - master
    paths:
      - '.yml'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04 
    

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install git -y
        sudo apt-get -y install autoconf automake autopoint bison build-essential flex gawk gettext git gperf libtool pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev texinfo python-docutils
    - name: Clone source code
      run: |
        cd /opt
        sudo git clone https://github.com/1056917561/padavan.git rt-n56u
        mkdir -p /opt/images/
    - name: build_toolchain
      run: |
        cd /opt/rt-n56u/toolchain-mipsel
        sudo ./clean_sources
        sudo ./build_toolchain
    #- name: build_toolchain-3.0.x
     # run: |
      #  sudo ./build_toolchain-3.0.x
    - name: build_toolchain-3.4.x
      run: |
        sudo ./build_toolchain-3.4.x
    
    - name: Build Firmware
      env:
        TNAME: n56ub1_base
      run: |
        cd /opt/rt-n56u/trunk
       
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        
        
        
        sudo ./clear_tree
        sudo ./build_firmware
    - name: copy file
      run: |
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages-new1
        path: /opt/images
